import type { Game } from "../types/types"

export const ListaGames: Game[] = [
  {
    id: "1",
    titulo: "Grand Theft Auto V",
    description:
      "Grand Theft Auto V es un videojuego de acción-aventura de mundo abierto desarrollado por Rockstar North y distribuido por Rockstar Games.",
    image:
      "https://oyster.ignimgs.com/mediawiki/apis.ign.com/grand-theft-auto-5/2/28/V_trevorfranklinmichael.jpg?width=640",
    videoURL: "https://www.youtube.com/embed/QkkoHAzjnUs",
    detalleImagenes: [
      "https://i.blogs.es/4d1062/gta-v/1366_2000.jpeg",
      "https://media.rockstargames.com/rockstargames/img/global/news/upload/GTAO640image.jpg",
      "https://i.blogs.es/0d5188/v-igg1-2880x1800/1366_2000.jpeg",
    ],
    rating: 4.8,
    precio: 59.99,
    categoria_id: 1,
    esta_oferta: true,
    estado: true,
    categorias: ["Action", "Crime"],
    plataformas: ["Windows", "PS5", "PS4"],
    ventas: [],
  },
  {
    id: "2",
    titulo: "Shadowfall",
    description: "A stealth-based ninja adventure with parkour mechanics and gripping narrative.",
    image: "https://picsum.photos/id/1005/400/250",
    videoURL: "https://www.w3schools.com/html/movie.mp4",
    detalleImagenes: [
      "https://picsum.photos/seed/shadow1/150",
      "https://picsum.photos/seed/shadow2/150",
      "https://picsum.photos/seed/shadow3/150",
    ],
    rating: 4.2,
    precio: 39.99,
    categoria_id: 2,
    esta_oferta: false,
    estado: true,
    categorias: ["Stealth", "Adventure", "Movement"],
    plataformas: ["PS5", "Switch"],
    ventas: [],
  },
  {
    id: "3",
    titulo: "Pixel Forge",
    description: "Build, craft, and survive in a voxel-based fantasy world full of secrets.",
    image: "https://picsum.photos/id/1025/400/250",
    videoURL: "https://www.w3schools.com/html/mov_bbb.mp4",
    detalleImagenes: [
      "https://picsum.photos/seed/pixel1/150",
      "https://picsum.photos/seed/pixel2/150",
      "https://picsum.photos/seed/pixel3/150",
    ],
    rating: 4.0,
    precio: 24.99,
    categoria_id: 3,
    esta_oferta: false,
    estado: true,
    categorias: ["Survival", "Builder", "Fantasy"],
    plataformas: ["Windows", "PS5", "MacOS"],
    ventas: [],
  },
  {
    id: "4",
    titulo: "RoboArena",
    description: "Fast-paced multiplayer battles with customizable mechs and explosive abilities.",
    image: "https://picsum.photos/id/1035/400/250",
    videoURL: "https://www.w3schools.com/html/movie.mp4",
    detalleImagenes: [
      "https://picsum.photos/seed/robo1/150",
      "https://picsum.photos/seed/robo2/150",
      "https://picsum.photos/seed/robo3/150",
    ],
    rating: 3.9,
    precio: 29.99,
    categoria_id: 4,
    esta_oferta: true,
    estado: true,
    categorias: ["Action", "Multiplayer", "FPS"],
    plataformas: ["Windows", "PS5", "Switch", "MacOS"],
    ventas: [],
  },
  {
    id: "5",
    titulo: "Silent Echo",
    description: "A psychological horror puzzle game where every sound could be your last.",
    image: "https://picsum.photos/id/1065/400/250",
    videoURL: "https://www.w3schools.com/html/mov_bbb.mp4",
    detalleImagenes: [
      "https://picsum.photos/seed/echo1/150",
      "https://picsum.photos/seed/echo2/150",
      "https://picsum.photos/seed/echo3/150",
    ],
    rating: 4.3,
    precio: 19.99,
    categoria_id: 5,
    esta_oferta: false,
    estado: true,
    categorias: ["Horror", "Puzzle"],
    plataformas: ["Windows", "PS5"],
    ventas: [],
  },
  {
    id: "6",
    titulo: "Neon Drift",
    description: "Race through futuristic cityscapes in gravity-defying anti-grav vehicles.",
    image: "https://picsum.photos/id/1045/400/250",
    videoURL: "https://www.w3schools.com/html/movie.mp4",
    detalleImagenes: [
      "https://picsum.photos/seed/neon1/150",
      "https://picsum.photos/seed/neon2/150",
      "https://picsum.photos/seed/neon3/150",
    ],
    rating: 4.1,
    precio: 34.99,
    categoria_id: 6,
    esta_oferta: true,
    estado: true,
    categorias: ["Racing", "Sci-Fi"],
    plataformas: ["Windows", "PS5", "Switch"],
    ventas: [],
  },
]
